### PR TITLE
Allowed filtering topics for HGrid

### PR DESCRIPTION
**Pull request by tishko0**

### CODE REVIEW

**Comment by dkamburov** [comment]
@tishko0 please resolve the conflict

**Review by MayaKirova — CHANGES_REQUESTED** [review]
There's some incorrect snippets for the hgrid:
image
This is in the Custom Operands section: http://localhost:3000/components/grids/hierarchical-grid/filtering.html#custom-filtering-operands
It should be setting `filters` property.

**Comment by MayaKirova** [comment]
There's a missing snippet for react in the styling section: http://localhost:3000/components/grids/hierarchical-grid/filtering.html#styling
image

**Comment by MayaKirova** [comment]
For Blazor, the snippet for styling at: http://localhost:3000/components/grids/hierarchical-grid/filtering.html#styling

Has wrong closing tag:
image

**Review by MayaKirova — APPROVED** [review]

**Pull request merged**
