### PR TITLE
Add cta banners

### PR DESCRIPTION
**Pull request by dobromirts**
Related to # https://github.com/IgniteUI/igniteui-docfx/issues/2637

### CODE REVIEW

**Comment by HUSSAR-mtrela** [comment]
@dobromirts is this PR ready for review/merge?

**Comment by dobromirts** [comment]
Yes, it is ready for review.

**Comment by HristoP96** [comment]
@HUSSAR-mtrela  we must update hte version of the template which applies these banners, thent he PR will be ready for review :)

**Review by HristoP96 — APPROVED** [review]

**Comment by HristoP96** [comment]
@HUSSAR-mtrela The PR is ready for merge now

**Pull request merged**
