### PR TITLE
[RELEASE] Updating production with latest changes.

### PR DESCRIPTION
**Pull request by ChronosSF**

### CODE REVIEW

**Comment by ChronosSF** [comment]
This will require merging the samples too. For all samples projects there are already PRs which are in test.

**Comment by HUSSAR-mtrela** [comment]
@mddifilippo89 @agoldenbaum  can you review this PR?

**Review by mddifilippo89 — APPROVED** [review]
https://github.com/IgniteUI/igniteui-xplat-docs/pull/1298

**Review by HUSSAR-mtrela — APPROVED** [review]

**Comment by HUSSAR-mtrela** [comment]
@ChronosSF merge this PR when your team is ready

**Comment by ChronosSF** [comment]
@kacheshmarova , adding in-test tag . Please, have your team test the documentation on staging before we push to prod.

**Pull request merged**
