### PR TITLE
Update seo cta banners

### PR DESCRIPTION
**Pull request by dobromirts**
Related to # https://github.com/IgniteUI/igniteui-docfx-template/issues/377

### CODE REVIEW

**Review by Volen99 — DISMISSED** [review]

**Comment by HUSSAR-mtrela** [comment]
this PR is blocked until Jason approved injecting those new marketing images in React/WC/Blazor docs

**Review by HUSSAR-mtrela — COMMENTED** [review]
this PR is blocked until Jason approved injecting those new marketing images in React/WC/Blazor docs

**Comment by zdrawku** [comment]
For Angular they are approved, whats the case for the other frameworks?

**Comment by aatanasov2** [comment]
Hi @HUSSAR-mtrela  @dobromirts  Jason and Holly discussed the banners last week and are OK with keeping them at the bottom of the pages. We want to see the performance of the banners and plan to resize them in the future if the performance is good (clicks, engagements, product trials)

**Comment by zdrawku** [comment]
In that case I am removing "do not merge" lable and @HUSSAR-mtrela may proceed with merging this change

**Comment by dobromirts** [comment]
@zdrawku this repositioning for react and blazor will be included in the new version of the template and when it is ready I will include it in this pull request.

**Comment by dobromirts** [comment]
Banners positioning changes for React and Blazor have been added to the new version and will be displayed before the last h2 header instead of at the bottom of the page as we discussed with @aatanasov2

**Review by Volen99 — APPROVED** [review]

**Comment by HUSSAR-mtrela** [comment]
@dobromirts did you re-position banners for WebCompnent platform as well?

**Comment by dobromirts** [comment]
> @dobromirts did you re-position banners for WebCompnent platform as well?

No they are going to remain the same, because currently we dont have a new banner for WC.

**Review by HUSSAR-mtrela — APPROVED** [review]

**Pull request merged**
